# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
v1 = np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
v2 = np.zeros(10)
v2[4] = 1
v2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
v3 = np.arange(10,50)
v3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
v4 = np.arange(10)
v4 = np.flip(v4)
v4

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
m1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [7]:
v5 = np.array([1,2,0,0,4,0])
i5 = np.nonzero(v5 > 0)
i5

(array([0, 1, 4]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
m2 = np.random.rand(3,3,3)
m2

array([[[0.19303507, 0.37749642, 0.2366497 ],
        [0.57116804, 0.74666214, 0.6359438 ],
        [0.19970649, 0.51410059, 0.76948699]],

       [[0.5984986 , 0.11659461, 0.78180252],
        [0.12219148, 0.64976638, 0.326112  ],
        [0.66968475, 0.00472809, 0.78230809]],

       [[0.1202332 , 0.75404857, 0.73966083],
        [0.62334988, 0.74274037, 0.60333525],
        [0.26305434, 0.9386622 , 0.63204972]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [9]:
m3 = np.random.rand(10,10)
m3

array([[0.72063279, 0.04689497, 0.87737625, 0.2990853 , 0.28670847,
        0.69273526, 0.04089523, 0.23544753, 0.9564087 , 0.59481213],
       [0.61944349, 0.12319707, 0.01372331, 0.96670715, 0.04308613,
        0.07277592, 0.51867481, 0.4913818 , 0.09238333, 0.14765202],
       [0.31638324, 0.06141918, 0.32288323, 0.07322396, 0.25997363,
        0.19289934, 0.14396694, 0.10634025, 0.82264539, 0.88871679],
       [0.04131978, 0.98593731, 0.85353526, 0.82581248, 0.43211449,
        0.10602743, 0.18514351, 0.93843737, 0.28318201, 0.6366913 ],
       [0.95423727, 0.20840921, 0.08632308, 0.01675459, 0.73799807,
        0.8388958 , 0.45683283, 0.01307935, 0.66815147, 0.6621369 ],
       [0.19526112, 0.05742962, 0.99447904, 0.95668972, 0.6710388 ,
        0.25576259, 0.31779655, 0.09342496, 0.73722324, 0.05209794],
       [0.03554522, 0.26296382, 0.85991517, 0.19435387, 0.64898498,
        0.18004444, 0.39193956, 0.69702788, 0.94740563, 0.33155049],
       [0.3997631 , 0.28008109, 0.0980508

In [10]:
print(m3.max())
print(m3.min())

0.9944790358285428
0.013079348227039933


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
v6 = np.random.rand(30)
v6

array([0.67526403, 0.88287889, 0.6784051 , 0.03175202, 0.19891139,
       0.31511017, 0.052351  , 0.26110538, 0.47541783, 0.41557723,
       0.18257076, 0.62177958, 0.48583922, 0.04842481, 0.05527417,
       0.55424405, 0.16643761, 0.21085586, 0.57489094, 0.04622707,
       0.70505651, 0.327175  , 0.52276191, 0.47919205, 0.62357588,
       0.75163146, 0.87239683, 0.86581036, 0.02609069, 0.02981071])

In [12]:
print(v6.mean())

0.40456061721450837


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
m4 = np.ones((3,3))
m4[1,1] = 0
m4

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [14]:
# Create a null array 2 ranks larger, and replace centre indices with array to create border of 0's
m5 = np.zeros((5,5))
m5[1:4, 1:4] = m4
m5

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
False, respectively

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
m6 = np.zeros((5,5))
m6[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
m6

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [17]:
m7 = np.random.rand(5,5)
m7_max = m7.max()
m7_min = m7.min()
m7 = (m7 - m7_min)/(m7_max - m7_min)
m7

array([[0.        , 0.7278746 , 0.81821234, 0.93352181, 0.58802221],
       [0.40787333, 0.73918533, 0.0166019 , 0.13203312, 0.02062499],
       [0.642512  , 0.26130699, 0.09381549, 0.10275658, 0.9679965 ],
       [0.5632992 , 0.8664475 , 1.        , 0.47956594, 0.17472616],
       [0.5281443 , 0.29786515, 0.66772509, 0.10287576, 0.73770222]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
v7 = np.random.randint(0,11, size=10)
neg = (v7 > 3) & (v7 < 8)
v7[neg] *= -1
v7

array([-7, -5, 10,  0, -5,  1, -7, -4,  9, 10])

#### 29. How to round away from zero a float array ? (★☆☆)

In [19]:
#not really sure what this question is asking, the wording is confusing.
rounded_array = np.round(v6, 2)
rounded_array

array([0.68, 0.88, 0.68, 0.03, 0.2 , 0.32, 0.05, 0.26, 0.48, 0.42, 0.18,
       0.62, 0.49, 0.05, 0.06, 0.55, 0.17, 0.21, 0.57, 0.05, 0.71, 0.33,
       0.52, 0.48, 0.62, 0.75, 0.87, 0.87, 0.03, 0.03])

#### 30. How to find common values between two arrays? (★☆☆)

In [20]:
v8 = np.random.randint(0,11, size=5)
v9 = np.random.randint(0,11, size=5)
print(v8)
print(v9)
com_val = np.intersect1d(v8,v9)
com_val

[7 1 6 9 6]
[2 2 6 0 2]


array([6])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No, it is False.

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [21]:
v10 = np.random.randint(100, size=10)
v10

array([26, 41, 78,  1, 54, 11, 11, 47,  8, 50])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [22]:
v11 = np.linspace(0,1,12)[1:11]
v11

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [23]:
v12 = np.random.random(10)
v12.sort()
v12

array([0.10315799, 0.30799792, 0.31826497, 0.36145022, 0.36452331,
       0.44912714, 0.48497382, 0.49071811, 0.69009817, 0.7412036 ])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [24]:
A = np.random.randint(0,5, size=5)
B = np.random.randint(0,5, size=5)
print(np.allclose(A,B))

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
v13 = np.random.randint(0,21, size=10)
print(v13)
v13[v13.argmax()] = 0
print(v13)

[12 11  8  3  7 11 13 12 12 12]
[12 11  8  3  7 11  0 12 12 12]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [26]:
scalar = 6.15
v14 = np.arange(20)
i = (np.abs(v14 - scalar)).argmin()
print(v14[i])

6


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [27]:
v15 = np.array([1.2,2.5,3.9,1.8,2.1,0.4,4.7,3.4])
v15 = v15.astype(int)
v15

array([1, 2, 3, 1, 2, 0, 4, 3])

#### 59. How to sort an array by the nth column? (★★☆)

In [28]:
m8 = np.random.randint(0,8, (3,3))
print(m8)
#found on stack overflow
nth_sort = m8[m8[:,1].argsort()]
print(nth_sort)
#I'd like to revisit this question at some point.
#To understand what is really being asked and an application possibly.

[[6 7 4]
 [2 7 2]
 [5 5 4]]
[[5 5 4]
 [6 7 4]
 [2 7 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [29]:
#use m8 from above
print((~m8.any(axis=0)).any())

False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [30]:
v16 = np.array([1,2,3,4,5])
print(v16)
x = 3
v16_ext = np.zeros(((len(v16)-1) * x) + len(v16))
print(v16_ext)
v16_ext[::4] = v16
print(v16_ext)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [31]:
m9 = np.random.randint(0,8, (3,3))
print(m9)
m9[[0,2]] = m9[[2,0]]
print(m9)

[[0 2 4]
 [3 6 3]
 [6 1 0]]
[[6 1 0]
 [3 6 3]
 [0 2 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [32]:
#change sign of float
v17 = np.array([1.07,-2.89,-7.64,5.21,8.69])
v17_neg = np.negative(v17)
v17_neg

array([-1.07,  2.89,  7.64, -5.21, -8.69])

In [33]:
#negate boolean
v18 = np.array([True,False,False,True,False,False,True,True,False,True])
v18_neg = np.logical_not(v18)
v18_neg

array([False,  True,  True, False,  True,  True, False, False,  True,
       False])

#### 83. How to find the most frequent value in an array?

In [34]:
v19 = np.array([1,2,3,4,4,5,6,7,8,8,8,9,10])
freq_val = np.bincount(v19).argmax()
print("Most frequent value is:", freq_val)

Most frequent value is: 8


#### 89. How to get the n largest values of an array (★★★)

In [35]:
#using array v19 above
#specify n largest values of the array in which you'd like to know.
n = 2
print(v19[np.argsort(v19)[-n:]])

[ 9 10]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [36]:
v20 = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]))

#extraxt first [0th] row
print(v20[0:1, 0:6])

#extraxt fourth [3rd] row
print(v20[3:4, 0:6])

[[1 2 3 4 5]]
[[16 17 18 19 20]]
